// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qmeta/transfer/v1/transfer.proto

package transferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerCheckRequest 服务器检查请求
type ServerCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCheckRequest) Reset() {
	*x = ServerCheckRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckRequest) ProtoMessage() {}

func (x *ServerCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCheckRequest.ProtoReflect.Descriptor instead.
func (*ServerCheckRequest) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *ServerCheckRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// ServerCheckResponse 服务器检查响应
type ServerCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCheckResponse) Reset() {
	*x = ServerCheckResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckResponse) ProtoMessage() {}

func (x *ServerCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCheckResponse.ProtoReflect.Descriptor instead.
func (*ServerCheckResponse) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCheckResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// FileMetadata 文件元数据
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Chunks        int64                  `protobuf:"varint,4,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Chunksize     int64                  `protobuf:"varint,5,opt,name=chunksize,proto3" json:"chunksize,omitempty"`
	Hash          string                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *FileMetadata) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetChunks() int64 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *FileMetadata) GetChunksize() int64 {
	if x != nil {
		return x.Chunksize
	}
	return 0
}

func (x *FileMetadata) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// ChunkData 文件块数据
type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Chunk         int64                  `protobuf:"varint,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkData) GetChunk() int64 {
	if x != nil {
		return x.Chunk
	}
	return 0
}

// UploadFileRequest 上传文件请求，包含文件元数据和文件块数据
type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFileRequest_Metadata
	//	*UploadFileRequest_Chunk
	Payload       isUploadFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFileRequest) GetPayload() isUploadFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() *ChunkData {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Payload interface {
	isUploadFileRequest_Payload()
}

type UploadFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk *ChunkData `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_Metadata) isUploadFileRequest_Payload() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Payload() {}

// UploadFileResponse 上传文件响应，包含元数据确认、块确认和传输结果
type UploadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFileResponse_MetaAck
	//	*UploadFileResponse_ChunkAck
	//	*UploadFileResponse_Result
	Payload       isUploadFileResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *UploadFileResponse) GetPayload() isUploadFileResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFileResponse) GetMetaAck() *MetaAck {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileResponse_MetaAck); ok {
			return x.MetaAck
		}
	}
	return nil
}

func (x *UploadFileResponse) GetChunkAck() *ChunkAck {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileResponse_ChunkAck); ok {
			return x.ChunkAck
		}
	}
	return nil
}

func (x *UploadFileResponse) GetResult() *TransferResult {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isUploadFileResponse_Payload interface {
	isUploadFileResponse_Payload()
}

type UploadFileResponse_MetaAck struct {
	MetaAck *MetaAck `protobuf:"bytes,1,opt,name=meta_ack,json=metaAck,proto3,oneof"`
}

type UploadFileResponse_ChunkAck struct {
	ChunkAck *ChunkAck `protobuf:"bytes,2,opt,name=chunk_ack,json=chunkAck,proto3,oneof"`
}

type UploadFileResponse_Result struct {
	Result *TransferResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*UploadFileResponse_MetaAck) isUploadFileResponse_Payload() {}

func (*UploadFileResponse_ChunkAck) isUploadFileResponse_Payload() {}

func (*UploadFileResponse_Result) isUploadFileResponse_Payload() {}

// MetaAck 元数据确认，服务器对文件元数据的响应
type MetaAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowUpload   bool                   `protobuf:"varint,1,opt,name=allow_upload,json=allowUpload,proto3" json:"allow_upload,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaAck) Reset() {
	*x = MetaAck{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaAck) ProtoMessage() {}

func (x *MetaAck) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaAck.ProtoReflect.Descriptor instead.
func (*MetaAck) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *MetaAck) GetAllowUpload() bool {
	if x != nil {
		return x.AllowUpload
	}
	return false
}

func (x *MetaAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChunkAck 块确认，服务器对文件块的响应
type ChunkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         int64                  `protobuf:"varint,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Received      bool                   `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkAck) Reset() {
	*x = ChunkAck{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkAck) ProtoMessage() {}

func (x *ChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkAck.ProtoReflect.Descriptor instead.
func (*ChunkAck) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkAck) GetChunk() int64 {
	if x != nil {
		return x.Chunk
	}
	return 0
}

func (x *ChunkAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

// TransferResult 传输结果，表示上传或下载的最终状态
type TransferResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResult) Reset() {
	*x = TransferResult{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResult) ProtoMessage() {}

func (x *TransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResult.ProtoReflect.Descriptor instead.
func (*TransferResult) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *TransferResult) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TransferResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DownloadFileRequest 下载文件请求，包含文件标识和块大小
type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Chunksize     int64                  `protobuf:"varint,3,opt,name=chunksize,proto3" json:"chunksize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadFileRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DownloadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownloadFileRequest) GetChunksize() int64 {
	if x != nil {
		return x.Chunksize
	}
	return 0
}

// DownloadFileResponse 下载文件响应，包含文件元数据、块数据和传输结果
type DownloadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DownloadFileResponse_Metadata
	//	*DownloadFileResponse_Chunk
	//	*DownloadFileResponse_Result
	Payload       isDownloadFileResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadFileResponse) GetPayload() isDownloadFileResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownloadFileResponse) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*DownloadFileResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DownloadFileResponse) GetChunk() *ChunkData {
	if x != nil {
		if x, ok := x.Payload.(*DownloadFileResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DownloadFileResponse) GetResult() *TransferResult {
	if x != nil {
		if x, ok := x.Payload.(*DownloadFileResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isDownloadFileResponse_Payload interface {
	isDownloadFileResponse_Payload()
}

type DownloadFileResponse_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type DownloadFileResponse_Chunk struct {
	Chunk *ChunkData `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type DownloadFileResponse_Result struct {
	Result *TransferResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*DownloadFileResponse_Metadata) isDownloadFileResponse_Payload() {}

func (*DownloadFileResponse_Chunk) isDownloadFileResponse_Payload() {}

func (*DownloadFileResponse_Result) isDownloadFileResponse_Payload() {}

// ListFileItem 列出文件项，包含文件名、大小、哈希值和修改时间
type ListFileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	ModifiedTime  int64                  `protobuf:"varint,4,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileItem) Reset() {
	*x = ListFileItem{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileItem) ProtoMessage() {}

func (x *ListFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileItem.ProtoReflect.Descriptor instead.
func (*ListFileItem) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{11}
}

func (x *ListFileItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListFileItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListFileItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ListFileItem) GetModifiedTime() int64 {
	if x != nil {
		return x.ModifiedTime
	}
	return 0
}

// ListFilesRequest 列出文件请求，包含文件标签
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{12}
}

func (x *ListFilesRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// ListFilesResponse 列出文件响应，包含状态、消息和文件列表
type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Files         []*ListFileItem        `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_qmeta_transfer_v1_transfer_proto_rawDescGZIP(), []int{13}
}

func (x *ListFilesResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ListFilesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListFilesResponse) GetFiles() []*ListFileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_qmeta_transfer_v1_transfer_proto protoreflect.FileDescriptor

const file_qmeta_transfer_v1_transfer_proto_rawDesc = "" +
	"\n" +
	" qmeta/transfer/v1/transfer.proto\x12\x11qmeta.transfer.v1\",\n" +
	"\x12ServerCheckRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"-\n" +
	"\x13ServerCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\x92\x01\n" +
	"\fFileMetadata\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06chunks\x18\x04 \x01(\x03R\x06chunks\x12\x1c\n" +
	"\tchunksize\x18\x05 \x01(\x03R\tchunksize\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\"5\n" +
	"\tChunkData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\x03R\x05chunk\"\x93\x01\n" +
	"\x11UploadFileRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.qmeta.transfer.v1.FileMetadataH\x00R\bmetadata\x124\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1c.qmeta.transfer.v1.ChunkDataH\x00R\x05chunkB\t\n" +
	"\apayload\"\xd1\x01\n" +
	"\x12UploadFileResponse\x127\n" +
	"\bmeta_ack\x18\x01 \x01(\v2\x1a.qmeta.transfer.v1.MetaAckH\x00R\ametaAck\x12:\n" +
	"\tchunk_ack\x18\x02 \x01(\v2\x1b.qmeta.transfer.v1.ChunkAckH\x00R\bchunkAck\x12;\n" +
	"\x06result\x18\x03 \x01(\v2!.qmeta.transfer.v1.TransferResultH\x00R\x06resultB\t\n" +
	"\apayload\"F\n" +
	"\aMetaAck\x12!\n" +
	"\fallow_upload\x18\x01 \x01(\bR\vallowUpload\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\bChunkAck\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\x03R\x05chunk\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\"B\n" +
	"\x0eTransferResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Y\n" +
	"\x13DownloadFileRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tchunksize\x18\x03 \x01(\x03R\tchunksize\"\xd3\x01\n" +
	"\x14DownloadFileResponse\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.qmeta.transfer.v1.FileMetadataH\x00R\bmetadata\x124\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1c.qmeta.transfer.v1.ChunkDataH\x00R\x05chunk\x12;\n" +
	"\x06result\x18\x03 \x01(\v2!.qmeta.transfer.v1.TransferResultH\x00R\x06resultB\t\n" +
	"\apayload\"o\n" +
	"\fListFileItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12#\n" +
	"\rmodified_time\x18\x04 \x01(\x03R\fmodifiedTime\"$\n" +
	"\x10ListFilesRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"|\n" +
	"\x11ListFilesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x05files\x18\x03 \x03(\v2\x1f.qmeta.transfer.v1.ListFileItemR\x05files2\x95\x03\n" +
	"\x13FileTransferService\x12^\n" +
	"\vServerCheck\x12%.qmeta.transfer.v1.ServerCheckRequest\x1a&.qmeta.transfer.v1.ServerCheckResponse\"\x00\x12X\n" +
	"\tListFiles\x12#.qmeta.transfer.v1.ListFilesRequest\x1a$.qmeta.transfer.v1.ListFilesResponse\"\x00\x12_\n" +
	"\n" +
	"UploadFile\x12$.qmeta.transfer.v1.UploadFileRequest\x1a%.qmeta.transfer.v1.UploadFileResponse\"\x00(\x010\x01\x12c\n" +
	"\fDownloadFile\x12&.qmeta.transfer.v1.DownloadFileRequest\x1a'.qmeta.transfer.v1.DownloadFileResponse\"\x000\x01B\xb6\x01\n" +
	"\x15com.qmeta.transfer.v1B\rTransferProtoP\x01Z(internal/pb/qmeta/transfer/v1;transferv1\xa2\x02\x03QTX\xaa\x02\x11Qmeta.Transfer.V1\xca\x02\x11Qmeta\\Transfer\\V1\xe2\x02\x1dQmeta\\Transfer\\V1\\GPBMetadata\xea\x02\x13Qmeta::Transfer::V1b\x06proto3"

var (
	file_qmeta_transfer_v1_transfer_proto_rawDescOnce sync.Once
	file_qmeta_transfer_v1_transfer_proto_rawDescData []byte
)

func file_qmeta_transfer_v1_transfer_proto_rawDescGZIP() []byte {
	file_qmeta_transfer_v1_transfer_proto_rawDescOnce.Do(func() {
		file_qmeta_transfer_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qmeta_transfer_v1_transfer_proto_rawDesc), len(file_qmeta_transfer_v1_transfer_proto_rawDesc)))
	})
	return file_qmeta_transfer_v1_transfer_proto_rawDescData
}

var file_qmeta_transfer_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_qmeta_transfer_v1_transfer_proto_goTypes = []any{
	(*ServerCheckRequest)(nil),   // 0: qmeta.transfer.v1.ServerCheckRequest
	(*ServerCheckResponse)(nil),  // 1: qmeta.transfer.v1.ServerCheckResponse
	(*FileMetadata)(nil),         // 2: qmeta.transfer.v1.FileMetadata
	(*ChunkData)(nil),            // 3: qmeta.transfer.v1.ChunkData
	(*UploadFileRequest)(nil),    // 4: qmeta.transfer.v1.UploadFileRequest
	(*UploadFileResponse)(nil),   // 5: qmeta.transfer.v1.UploadFileResponse
	(*MetaAck)(nil),              // 6: qmeta.transfer.v1.MetaAck
	(*ChunkAck)(nil),             // 7: qmeta.transfer.v1.ChunkAck
	(*TransferResult)(nil),       // 8: qmeta.transfer.v1.TransferResult
	(*DownloadFileRequest)(nil),  // 9: qmeta.transfer.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil), // 10: qmeta.transfer.v1.DownloadFileResponse
	(*ListFileItem)(nil),         // 11: qmeta.transfer.v1.ListFileItem
	(*ListFilesRequest)(nil),     // 12: qmeta.transfer.v1.ListFilesRequest
	(*ListFilesResponse)(nil),    // 13: qmeta.transfer.v1.ListFilesResponse
}
var file_qmeta_transfer_v1_transfer_proto_depIdxs = []int32{
	2,  // 0: qmeta.transfer.v1.UploadFileRequest.metadata:type_name -> qmeta.transfer.v1.FileMetadata
	3,  // 1: qmeta.transfer.v1.UploadFileRequest.chunk:type_name -> qmeta.transfer.v1.ChunkData
	6,  // 2: qmeta.transfer.v1.UploadFileResponse.meta_ack:type_name -> qmeta.transfer.v1.MetaAck
	7,  // 3: qmeta.transfer.v1.UploadFileResponse.chunk_ack:type_name -> qmeta.transfer.v1.ChunkAck
	8,  // 4: qmeta.transfer.v1.UploadFileResponse.result:type_name -> qmeta.transfer.v1.TransferResult
	2,  // 5: qmeta.transfer.v1.DownloadFileResponse.metadata:type_name -> qmeta.transfer.v1.FileMetadata
	3,  // 6: qmeta.transfer.v1.DownloadFileResponse.chunk:type_name -> qmeta.transfer.v1.ChunkData
	8,  // 7: qmeta.transfer.v1.DownloadFileResponse.result:type_name -> qmeta.transfer.v1.TransferResult
	11, // 8: qmeta.transfer.v1.ListFilesResponse.files:type_name -> qmeta.transfer.v1.ListFileItem
	0,  // 9: qmeta.transfer.v1.FileTransferService.ServerCheck:input_type -> qmeta.transfer.v1.ServerCheckRequest
	12, // 10: qmeta.transfer.v1.FileTransferService.ListFiles:input_type -> qmeta.transfer.v1.ListFilesRequest
	4,  // 11: qmeta.transfer.v1.FileTransferService.UploadFile:input_type -> qmeta.transfer.v1.UploadFileRequest
	9,  // 12: qmeta.transfer.v1.FileTransferService.DownloadFile:input_type -> qmeta.transfer.v1.DownloadFileRequest
	1,  // 13: qmeta.transfer.v1.FileTransferService.ServerCheck:output_type -> qmeta.transfer.v1.ServerCheckResponse
	13, // 14: qmeta.transfer.v1.FileTransferService.ListFiles:output_type -> qmeta.transfer.v1.ListFilesResponse
	5,  // 15: qmeta.transfer.v1.FileTransferService.UploadFile:output_type -> qmeta.transfer.v1.UploadFileResponse
	10, // 16: qmeta.transfer.v1.FileTransferService.DownloadFile:output_type -> qmeta.transfer.v1.DownloadFileResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_qmeta_transfer_v1_transfer_proto_init() }
func file_qmeta_transfer_v1_transfer_proto_init() {
	if File_qmeta_transfer_v1_transfer_proto != nil {
		return
	}
	file_qmeta_transfer_v1_transfer_proto_msgTypes[4].OneofWrappers = []any{
		(*UploadFileRequest_Metadata)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	file_qmeta_transfer_v1_transfer_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadFileResponse_MetaAck)(nil),
		(*UploadFileResponse_ChunkAck)(nil),
		(*UploadFileResponse_Result)(nil),
	}
	file_qmeta_transfer_v1_transfer_proto_msgTypes[10].OneofWrappers = []any{
		(*DownloadFileResponse_Metadata)(nil),
		(*DownloadFileResponse_Chunk)(nil),
		(*DownloadFileResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qmeta_transfer_v1_transfer_proto_rawDesc), len(file_qmeta_transfer_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qmeta_transfer_v1_transfer_proto_goTypes,
		DependencyIndexes: file_qmeta_transfer_v1_transfer_proto_depIdxs,
		MessageInfos:      file_qmeta_transfer_v1_transfer_proto_msgTypes,
	}.Build()
	File_qmeta_transfer_v1_transfer_proto = out.File
	file_qmeta_transfer_v1_transfer_proto_goTypes = nil
	file_qmeta_transfer_v1_transfer_proto_depIdxs = nil
}
