// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qmeta/transfer/v1/transfer.proto

package transferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerCheckRequest 服务器检查请求
type ServerCheckRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      bool                   `protobuf:"varint,1,opt,name=status"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServerCheckRequest) Reset() {
	*x = ServerCheckRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckRequest) ProtoMessage() {}

func (x *ServerCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServerCheckRequest) GetStatus() bool {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return false
}

func (x *ServerCheckRequest) SetStatus(v bool) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServerCheckRequest) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServerCheckRequest) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = false
}

type ServerCheckRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *bool
}

func (b0 ServerCheckRequest_builder) Build() *ServerCheckRequest {
	m0 := &ServerCheckRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Status = *b.Status
	}
	return m0
}

// ServerCheckResponse 服务器检查响应
type ServerCheckResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      bool                   `protobuf:"varint,1,opt,name=status"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServerCheckResponse) Reset() {
	*x = ServerCheckResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckResponse) ProtoMessage() {}

func (x *ServerCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServerCheckResponse) GetStatus() bool {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return false
}

func (x *ServerCheckResponse) SetStatus(v bool) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServerCheckResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServerCheckResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = false
}

type ServerCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *bool
}

func (b0 ServerCheckResponse_builder) Build() *ServerCheckResponse {
	m0 := &ServerCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Status = *b.Status
	}
	return m0
}

// FileMetadata 文件元数据
type FileMetadata struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tag         *string                `protobuf:"bytes,1,opt,name=tag"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Size        int64                  `protobuf:"varint,3,opt,name=size"`
	xxx_hidden_Chunks      int64                  `protobuf:"varint,4,opt,name=chunks"`
	xxx_hidden_Chunksize   int64                  `protobuf:"varint,5,opt,name=chunksize"`
	xxx_hidden_Hash        *string                `protobuf:"bytes,6,opt,name=hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileMetadata) GetTag() string {
	if x != nil {
		if x.xxx_hidden_Tag != nil {
			return *x.xxx_hidden_Tag
		}
		return ""
	}
	return ""
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *FileMetadata) GetChunks() int64 {
	if x != nil {
		return x.xxx_hidden_Chunks
	}
	return 0
}

func (x *FileMetadata) GetChunksize() int64 {
	if x != nil {
		return x.xxx_hidden_Chunksize
	}
	return 0
}

func (x *FileMetadata) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *FileMetadata) SetTag(v string) {
	x.xxx_hidden_Tag = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *FileMetadata) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *FileMetadata) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *FileMetadata) SetChunks(v int64) {
	x.xxx_hidden_Chunks = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *FileMetadata) SetChunksize(v int64) {
	x.xxx_hidden_Chunksize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *FileMetadata) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *FileMetadata) HasTag() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FileMetadata) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FileMetadata) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FileMetadata) HasChunks() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *FileMetadata) HasChunksize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *FileMetadata) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *FileMetadata) ClearTag() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Tag = nil
}

func (x *FileMetadata) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *FileMetadata) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Size = 0
}

func (x *FileMetadata) ClearChunks() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Chunks = 0
}

func (x *FileMetadata) ClearChunksize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Chunksize = 0
}

func (x *FileMetadata) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Hash = nil
}

type FileMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tag       *string
	Name      *string
	Size      *int64
	Chunks    *int64
	Chunksize *int64
	Hash      *string
}

func (b0 FileMetadata_builder) Build() *FileMetadata {
	m0 := &FileMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Tag != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Tag = b.Tag
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Size = *b.Size
	}
	if b.Chunks != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Chunks = *b.Chunks
	}
	if b.Chunksize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Chunksize = *b.Chunksize
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Hash = b.Hash
	}
	return m0
}

// ChunkData 文件块数据
type ChunkData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Chunk       int64                  `protobuf:"varint,2,opt,name=chunk"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ChunkData) GetChunk() int64 {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return 0
}

func (x *ChunkData) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ChunkData) SetChunk(v int64) {
	x.xxx_hidden_Chunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ChunkData) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChunkData) HasChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChunkData) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

func (x *ChunkData) ClearChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Chunk = 0
}

type ChunkData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data  []byte
	Chunk *int64
}

func (b0 ChunkData_builder) Build() *ChunkData {
	m0 := &ChunkData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Data = b.Data
	}
	if b.Chunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Chunk = *b.Chunk
	}
	return m0
}

// UploadFileRequest 上传文件请求，包含文件元数据和文件块数据
type UploadFileRequest struct {
	state              protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Payload isUploadFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() *ChunkData {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *UploadFileRequest) SetMetadata(v *FileMetadata) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadFileRequest_Metadata{v}
}

func (x *UploadFileRequest) SetChunk(v *ChunkData) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadFileRequest_Chunk{v}
}

func (x *UploadFileRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *UploadFileRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Metadata)
	return ok
}

func (x *UploadFileRequest) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Chunk)
	return ok
}

func (x *UploadFileRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *UploadFileRequest) ClearMetadata() {
	if _, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Metadata); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *UploadFileRequest) ClearChunk() {
	if _, ok := x.xxx_hidden_Payload.(*uploadFileRequest_Chunk); ok {
		x.xxx_hidden_Payload = nil
	}
}

const UploadFileRequest_Payload_not_set_case case_UploadFileRequest_Payload = 0
const UploadFileRequest_Metadata_case case_UploadFileRequest_Payload = 1
const UploadFileRequest_Chunk_case case_UploadFileRequest_Payload = 2

func (x *UploadFileRequest) WhichPayload() case_UploadFileRequest_Payload {
	if x == nil {
		return UploadFileRequest_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *uploadFileRequest_Metadata:
		return UploadFileRequest_Metadata_case
	case *uploadFileRequest_Chunk:
		return UploadFileRequest_Chunk_case
	default:
		return UploadFileRequest_Payload_not_set_case
	}
}

type UploadFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	Metadata *FileMetadata
	Chunk    *ChunkData
	// -- end of xxx_hidden_Payload
}

func (b0 UploadFileRequest_builder) Build() *UploadFileRequest {
	m0 := &UploadFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Metadata != nil {
		x.xxx_hidden_Payload = &uploadFileRequest_Metadata{b.Metadata}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Payload = &uploadFileRequest_Chunk{b.Chunk}
	}
	return m0
}

type case_UploadFileRequest_Payload protoreflect.FieldNumber

func (x case_UploadFileRequest_Payload) String() string {
	md := file_qmeta_transfer_v1_transfer_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadFileRequest_Payload interface {
	isUploadFileRequest_Payload()
}

type uploadFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,oneof"`
}

type uploadFileRequest_Chunk struct {
	Chunk *ChunkData `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

func (*uploadFileRequest_Metadata) isUploadFileRequest_Payload() {}

func (*uploadFileRequest_Chunk) isUploadFileRequest_Payload() {}

// UploadFileResponse 上传文件响应，包含元数据确认、块确认和传输结果
type UploadFileResponse struct {
	state              protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Payload isUploadFileResponse_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadFileResponse) GetMetaAck() *MetaAck {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadFileResponse_MetaAck); ok {
			return x.MetaAck
		}
	}
	return nil
}

func (x *UploadFileResponse) GetChunkAck() *ChunkAck {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadFileResponse_ChunkAck); ok {
			return x.ChunkAck
		}
	}
	return nil
}

func (x *UploadFileResponse) GetResult() *TransferResult {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*uploadFileResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *UploadFileResponse) SetMetaAck(v *MetaAck) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadFileResponse_MetaAck{v}
}

func (x *UploadFileResponse) SetChunkAck(v *ChunkAck) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadFileResponse_ChunkAck{v}
}

func (x *UploadFileResponse) SetResult(v *TransferResult) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &uploadFileResponse_Result{v}
}

func (x *UploadFileResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *UploadFileResponse) HasMetaAck() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadFileResponse_MetaAck)
	return ok
}

func (x *UploadFileResponse) HasChunkAck() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadFileResponse_ChunkAck)
	return ok
}

func (x *UploadFileResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*uploadFileResponse_Result)
	return ok
}

func (x *UploadFileResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *UploadFileResponse) ClearMetaAck() {
	if _, ok := x.xxx_hidden_Payload.(*uploadFileResponse_MetaAck); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *UploadFileResponse) ClearChunkAck() {
	if _, ok := x.xxx_hidden_Payload.(*uploadFileResponse_ChunkAck); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *UploadFileResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Payload.(*uploadFileResponse_Result); ok {
		x.xxx_hidden_Payload = nil
	}
}

const UploadFileResponse_Payload_not_set_case case_UploadFileResponse_Payload = 0
const UploadFileResponse_MetaAck_case case_UploadFileResponse_Payload = 1
const UploadFileResponse_ChunkAck_case case_UploadFileResponse_Payload = 2
const UploadFileResponse_Result_case case_UploadFileResponse_Payload = 3

func (x *UploadFileResponse) WhichPayload() case_UploadFileResponse_Payload {
	if x == nil {
		return UploadFileResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *uploadFileResponse_MetaAck:
		return UploadFileResponse_MetaAck_case
	case *uploadFileResponse_ChunkAck:
		return UploadFileResponse_ChunkAck_case
	case *uploadFileResponse_Result:
		return UploadFileResponse_Result_case
	default:
		return UploadFileResponse_Payload_not_set_case
	}
}

type UploadFileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	MetaAck  *MetaAck
	ChunkAck *ChunkAck
	Result   *TransferResult
	// -- end of xxx_hidden_Payload
}

func (b0 UploadFileResponse_builder) Build() *UploadFileResponse {
	m0 := &UploadFileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MetaAck != nil {
		x.xxx_hidden_Payload = &uploadFileResponse_MetaAck{b.MetaAck}
	}
	if b.ChunkAck != nil {
		x.xxx_hidden_Payload = &uploadFileResponse_ChunkAck{b.ChunkAck}
	}
	if b.Result != nil {
		x.xxx_hidden_Payload = &uploadFileResponse_Result{b.Result}
	}
	return m0
}

type case_UploadFileResponse_Payload protoreflect.FieldNumber

func (x case_UploadFileResponse_Payload) String() string {
	md := file_qmeta_transfer_v1_transfer_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadFileResponse_Payload interface {
	isUploadFileResponse_Payload()
}

type uploadFileResponse_MetaAck struct {
	MetaAck *MetaAck `protobuf:"bytes,1,opt,name=meta_ack,json=metaAck,oneof"`
}

type uploadFileResponse_ChunkAck struct {
	ChunkAck *ChunkAck `protobuf:"bytes,2,opt,name=chunk_ack,json=chunkAck,oneof"`
}

type uploadFileResponse_Result struct {
	Result *TransferResult `protobuf:"bytes,3,opt,name=result,oneof"`
}

func (*uploadFileResponse_MetaAck) isUploadFileResponse_Payload() {}

func (*uploadFileResponse_ChunkAck) isUploadFileResponse_Payload() {}

func (*uploadFileResponse_Result) isUploadFileResponse_Payload() {}

// MetaAck 元数据确认，服务器对文件元数据的响应
type MetaAck struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AllowUpload bool                   `protobuf:"varint,1,opt,name=allow_upload,json=allowUpload"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MetaAck) Reset() {
	*x = MetaAck{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaAck) ProtoMessage() {}

func (x *MetaAck) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetaAck) GetAllowUpload() bool {
	if x != nil {
		return x.xxx_hidden_AllowUpload
	}
	return false
}

func (x *MetaAck) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *MetaAck) SetAllowUpload(v bool) {
	x.xxx_hidden_AllowUpload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *MetaAck) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *MetaAck) HasAllowUpload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MetaAck) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MetaAck) ClearAllowUpload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AllowUpload = false
}

func (x *MetaAck) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type MetaAck_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AllowUpload *bool
	Message     *string
}

func (b0 MetaAck_builder) Build() *MetaAck {
	m0 := &MetaAck{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AllowUpload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_AllowUpload = *b.AllowUpload
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

// ChunkAck 块确认，服务器对文件块的响应
type ChunkAck struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Chunk       int64                  `protobuf:"varint,1,opt,name=chunk"`
	xxx_hidden_Received    bool                   `protobuf:"varint,2,opt,name=received"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChunkAck) Reset() {
	*x = ChunkAck{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkAck) ProtoMessage() {}

func (x *ChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChunkAck) GetChunk() int64 {
	if x != nil {
		return x.xxx_hidden_Chunk
	}
	return 0
}

func (x *ChunkAck) GetReceived() bool {
	if x != nil {
		return x.xxx_hidden_Received
	}
	return false
}

func (x *ChunkAck) SetChunk(v int64) {
	x.xxx_hidden_Chunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ChunkAck) SetReceived(v bool) {
	x.xxx_hidden_Received = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ChunkAck) HasChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChunkAck) HasReceived() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChunkAck) ClearChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Chunk = 0
}

func (x *ChunkAck) ClearReceived() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Received = false
}

type ChunkAck_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Chunk    *int64
	Received *bool
}

func (b0 ChunkAck_builder) Build() *ChunkAck {
	m0 := &ChunkAck{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Chunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Chunk = *b.Chunk
	}
	if b.Received != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Received = *b.Received
	}
	return m0
}

// TransferResult 传输结果，表示上传或下载的最终状态
type TransferResult struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      bool                   `protobuf:"varint,1,opt,name=status"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransferResult) Reset() {
	*x = TransferResult{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResult) ProtoMessage() {}

func (x *TransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TransferResult) GetStatus() bool {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return false
}

func (x *TransferResult) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *TransferResult) SetStatus(v bool) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *TransferResult) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *TransferResult) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TransferResult) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TransferResult) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = false
}

func (x *TransferResult) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type TransferResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  *bool
	Message *string
}

func (b0 TransferResult_builder) Build() *TransferResult {
	m0 := &TransferResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = *b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

// DownloadFileRequest 下载文件请求，包含文件标识和块大小
type DownloadFileRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tag         *string                `protobuf:"bytes,1,opt,name=tag"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Chunksize   int64                  `protobuf:"varint,3,opt,name=chunksize"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadFileRequest) GetTag() string {
	if x != nil {
		if x.xxx_hidden_Tag != nil {
			return *x.xxx_hidden_Tag
		}
		return ""
	}
	return ""
}

func (x *DownloadFileRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DownloadFileRequest) GetChunksize() int64 {
	if x != nil {
		return x.xxx_hidden_Chunksize
	}
	return 0
}

func (x *DownloadFileRequest) SetTag(v string) {
	x.xxx_hidden_Tag = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *DownloadFileRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DownloadFileRequest) SetChunksize(v int64) {
	x.xxx_hidden_Chunksize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *DownloadFileRequest) HasTag() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadFileRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DownloadFileRequest) HasChunksize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DownloadFileRequest) ClearTag() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Tag = nil
}

func (x *DownloadFileRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *DownloadFileRequest) ClearChunksize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Chunksize = 0
}

type DownloadFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tag       *string
	Name      *string
	Chunksize *int64
}

func (b0 DownloadFileRequest_builder) Build() *DownloadFileRequest {
	m0 := &DownloadFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Tag != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Tag = b.Tag
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Chunksize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Chunksize = *b.Chunksize
	}
	return m0
}

// DownloadFileResponse 下载文件响应，包含文件元数据、块数据和传输结果
type DownloadFileResponse struct {
	state              protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Payload isDownloadFileResponse_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadFileResponse) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DownloadFileResponse) GetChunk() *ChunkData {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *DownloadFileResponse) GetResult() *TransferResult {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *DownloadFileResponse) SetMetadata(v *FileMetadata) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &downloadFileResponse_Metadata{v}
}

func (x *DownloadFileResponse) SetChunk(v *ChunkData) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &downloadFileResponse_Chunk{v}
}

func (x *DownloadFileResponse) SetResult(v *TransferResult) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &downloadFileResponse_Result{v}
}

func (x *DownloadFileResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *DownloadFileResponse) HasMetadata() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Metadata)
	return ok
}

func (x *DownloadFileResponse) HasChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Chunk)
	return ok
}

func (x *DownloadFileResponse) HasResult() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Result)
	return ok
}

func (x *DownloadFileResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *DownloadFileResponse) ClearMetadata() {
	if _, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Metadata); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *DownloadFileResponse) ClearChunk() {
	if _, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Chunk); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *DownloadFileResponse) ClearResult() {
	if _, ok := x.xxx_hidden_Payload.(*downloadFileResponse_Result); ok {
		x.xxx_hidden_Payload = nil
	}
}

const DownloadFileResponse_Payload_not_set_case case_DownloadFileResponse_Payload = 0
const DownloadFileResponse_Metadata_case case_DownloadFileResponse_Payload = 1
const DownloadFileResponse_Chunk_case case_DownloadFileResponse_Payload = 2
const DownloadFileResponse_Result_case case_DownloadFileResponse_Payload = 3

func (x *DownloadFileResponse) WhichPayload() case_DownloadFileResponse_Payload {
	if x == nil {
		return DownloadFileResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *downloadFileResponse_Metadata:
		return DownloadFileResponse_Metadata_case
	case *downloadFileResponse_Chunk:
		return DownloadFileResponse_Chunk_case
	case *downloadFileResponse_Result:
		return DownloadFileResponse_Result_case
	default:
		return DownloadFileResponse_Payload_not_set_case
	}
}

type DownloadFileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	Metadata *FileMetadata
	Chunk    *ChunkData
	Result   *TransferResult
	// -- end of xxx_hidden_Payload
}

func (b0 DownloadFileResponse_builder) Build() *DownloadFileResponse {
	m0 := &DownloadFileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Metadata != nil {
		x.xxx_hidden_Payload = &downloadFileResponse_Metadata{b.Metadata}
	}
	if b.Chunk != nil {
		x.xxx_hidden_Payload = &downloadFileResponse_Chunk{b.Chunk}
	}
	if b.Result != nil {
		x.xxx_hidden_Payload = &downloadFileResponse_Result{b.Result}
	}
	return m0
}

type case_DownloadFileResponse_Payload protoreflect.FieldNumber

func (x case_DownloadFileResponse_Payload) String() string {
	md := file_qmeta_transfer_v1_transfer_proto_msgTypes[10].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDownloadFileResponse_Payload interface {
	isDownloadFileResponse_Payload()
}

type downloadFileResponse_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,oneof"`
}

type downloadFileResponse_Chunk struct {
	Chunk *ChunkData `protobuf:"bytes,2,opt,name=chunk,oneof"`
}

type downloadFileResponse_Result struct {
	Result *TransferResult `protobuf:"bytes,3,opt,name=result,oneof"`
}

func (*downloadFileResponse_Metadata) isDownloadFileResponse_Payload() {}

func (*downloadFileResponse_Chunk) isDownloadFileResponse_Payload() {}

func (*downloadFileResponse_Result) isDownloadFileResponse_Payload() {}

// ListFileItem 列出文件项，包含文件名、大小、哈希值和修改时间
type ListFileItem struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Size         int64                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_Hash         *string                `protobuf:"bytes,3,opt,name=hash"`
	xxx_hidden_ModifiedTime int64                  `protobuf:"varint,4,opt,name=modified_time,json=modifiedTime"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListFileItem) Reset() {
	*x = ListFileItem{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileItem) ProtoMessage() {}

func (x *ListFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListFileItem) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ListFileItem) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *ListFileItem) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *ListFileItem) GetModifiedTime() int64 {
	if x != nil {
		return x.xxx_hidden_ModifiedTime
	}
	return 0
}

func (x *ListFileItem) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ListFileItem) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ListFileItem) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ListFileItem) SetModifiedTime(v int64) {
	x.xxx_hidden_ModifiedTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ListFileItem) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListFileItem) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListFileItem) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListFileItem) HasModifiedTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ListFileItem) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ListFileItem) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *ListFileItem) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Hash = nil
}

func (x *ListFileItem) ClearModifiedTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ModifiedTime = 0
}

type ListFileItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         *string
	Size         *int64
	Hash         *string
	ModifiedTime *int64
}

func (b0 ListFileItem_builder) Build() *ListFileItem {
	m0 := &ListFileItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Size = *b.Size
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Hash = b.Hash
	}
	if b.ModifiedTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ModifiedTime = *b.ModifiedTime
	}
	return m0
}

// ListFilesRequest 列出文件请求，包含文件标签
type ListFilesRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tag         *string                `protobuf:"bytes,1,opt,name=tag"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListFilesRequest) GetTag() string {
	if x != nil {
		if x.xxx_hidden_Tag != nil {
			return *x.xxx_hidden_Tag
		}
		return ""
	}
	return ""
}

func (x *ListFilesRequest) SetTag(v string) {
	x.xxx_hidden_Tag = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ListFilesRequest) HasTag() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListFilesRequest) ClearTag() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Tag = nil
}

type ListFilesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tag *string
}

func (b0 ListFilesRequest_builder) Build() *ListFilesRequest {
	m0 := &ListFilesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Tag != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Tag = b.Tag
	}
	return m0
}

// ListFilesResponse 列出文件响应，包含状态、消息和文件列表
type ListFilesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      bool                   `protobuf:"varint,1,opt,name=status"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_Files       *[]*ListFileItem       `protobuf:"bytes,3,rep,name=files"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qmeta_transfer_v1_transfer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListFilesResponse) GetStatus() bool {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return false
}

func (x *ListFilesResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ListFilesResponse) GetFiles() []*ListFileItem {
	if x != nil {
		if x.xxx_hidden_Files != nil {
			return *x.xxx_hidden_Files
		}
	}
	return nil
}

func (x *ListFilesResponse) SetStatus(v bool) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ListFilesResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListFilesResponse) SetFiles(v []*ListFileItem) {
	x.xxx_hidden_Files = &v
}

func (x *ListFilesResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListFilesResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListFilesResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = false
}

func (x *ListFilesResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ListFilesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  *bool
	Message *string
	Files   []*ListFileItem
}

func (b0 ListFilesResponse_builder) Build() *ListFilesResponse {
	m0 := &ListFilesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Status = *b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_Files = &b.Files
	return m0
}

var File_qmeta_transfer_v1_transfer_proto protoreflect.FileDescriptor

const file_qmeta_transfer_v1_transfer_proto_rawDesc = "" +
	"\n" +
	" qmeta/transfer/v1/transfer.proto\x12\x11qmeta.transfer.v1\",\n" +
	"\x12ServerCheckRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"-\n" +
	"\x13ServerCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\x92\x01\n" +
	"\fFileMetadata\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06chunks\x18\x04 \x01(\x03R\x06chunks\x12\x1c\n" +
	"\tchunksize\x18\x05 \x01(\x03R\tchunksize\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\"5\n" +
	"\tChunkData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\x03R\x05chunk\"\x93\x01\n" +
	"\x11UploadFileRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.qmeta.transfer.v1.FileMetadataH\x00R\bmetadata\x124\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1c.qmeta.transfer.v1.ChunkDataH\x00R\x05chunkB\t\n" +
	"\apayload\"\xd1\x01\n" +
	"\x12UploadFileResponse\x127\n" +
	"\bmeta_ack\x18\x01 \x01(\v2\x1a.qmeta.transfer.v1.MetaAckH\x00R\ametaAck\x12:\n" +
	"\tchunk_ack\x18\x02 \x01(\v2\x1b.qmeta.transfer.v1.ChunkAckH\x00R\bchunkAck\x12;\n" +
	"\x06result\x18\x03 \x01(\v2!.qmeta.transfer.v1.TransferResultH\x00R\x06resultB\t\n" +
	"\apayload\"F\n" +
	"\aMetaAck\x12!\n" +
	"\fallow_upload\x18\x01 \x01(\bR\vallowUpload\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\bChunkAck\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\x03R\x05chunk\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\"B\n" +
	"\x0eTransferResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Y\n" +
	"\x13DownloadFileRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tchunksize\x18\x03 \x01(\x03R\tchunksize\"\xd3\x01\n" +
	"\x14DownloadFileResponse\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.qmeta.transfer.v1.FileMetadataH\x00R\bmetadata\x124\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1c.qmeta.transfer.v1.ChunkDataH\x00R\x05chunk\x12;\n" +
	"\x06result\x18\x03 \x01(\v2!.qmeta.transfer.v1.TransferResultH\x00R\x06resultB\t\n" +
	"\apayload\"o\n" +
	"\fListFileItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12#\n" +
	"\rmodified_time\x18\x04 \x01(\x03R\fmodifiedTime\"$\n" +
	"\x10ListFilesRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"|\n" +
	"\x11ListFilesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x05files\x18\x03 \x03(\v2\x1f.qmeta.transfer.v1.ListFileItemR\x05files2\x95\x03\n" +
	"\x13FileTransferService\x12^\n" +
	"\vServerCheck\x12%.qmeta.transfer.v1.ServerCheckRequest\x1a&.qmeta.transfer.v1.ServerCheckResponse\"\x00\x12X\n" +
	"\tListFiles\x12#.qmeta.transfer.v1.ListFilesRequest\x1a$.qmeta.transfer.v1.ListFilesResponse\"\x00\x12_\n" +
	"\n" +
	"UploadFile\x12$.qmeta.transfer.v1.UploadFileRequest\x1a%.qmeta.transfer.v1.UploadFileResponse\"\x00(\x010\x01\x12c\n" +
	"\fDownloadFile\x12&.qmeta.transfer.v1.DownloadFileRequest\x1a'.qmeta.transfer.v1.DownloadFileResponse\"\x000\x01B\xb6\x01\n" +
	"\x15com.qmeta.transfer.v1B\rTransferProtoP\x01Z(internal/pb/qmeta/transfer/v1;transferv1\xa2\x02\x03QTX\xaa\x02\x11Qmeta.Transfer.V1\xca\x02\x11Qmeta\\Transfer\\V1\xe2\x02\x1dQmeta\\Transfer\\V1\\GPBMetadata\xea\x02\x13Qmeta::Transfer::V1b\beditionsp\xe9\a"

var file_qmeta_transfer_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_qmeta_transfer_v1_transfer_proto_goTypes = []any{
	(*ServerCheckRequest)(nil),   // 0: qmeta.transfer.v1.ServerCheckRequest
	(*ServerCheckResponse)(nil),  // 1: qmeta.transfer.v1.ServerCheckResponse
	(*FileMetadata)(nil),         // 2: qmeta.transfer.v1.FileMetadata
	(*ChunkData)(nil),            // 3: qmeta.transfer.v1.ChunkData
	(*UploadFileRequest)(nil),    // 4: qmeta.transfer.v1.UploadFileRequest
	(*UploadFileResponse)(nil),   // 5: qmeta.transfer.v1.UploadFileResponse
	(*MetaAck)(nil),              // 6: qmeta.transfer.v1.MetaAck
	(*ChunkAck)(nil),             // 7: qmeta.transfer.v1.ChunkAck
	(*TransferResult)(nil),       // 8: qmeta.transfer.v1.TransferResult
	(*DownloadFileRequest)(nil),  // 9: qmeta.transfer.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil), // 10: qmeta.transfer.v1.DownloadFileResponse
	(*ListFileItem)(nil),         // 11: qmeta.transfer.v1.ListFileItem
	(*ListFilesRequest)(nil),     // 12: qmeta.transfer.v1.ListFilesRequest
	(*ListFilesResponse)(nil),    // 13: qmeta.transfer.v1.ListFilesResponse
}
var file_qmeta_transfer_v1_transfer_proto_depIdxs = []int32{
	2,  // 0: qmeta.transfer.v1.UploadFileRequest.metadata:type_name -> qmeta.transfer.v1.FileMetadata
	3,  // 1: qmeta.transfer.v1.UploadFileRequest.chunk:type_name -> qmeta.transfer.v1.ChunkData
	6,  // 2: qmeta.transfer.v1.UploadFileResponse.meta_ack:type_name -> qmeta.transfer.v1.MetaAck
	7,  // 3: qmeta.transfer.v1.UploadFileResponse.chunk_ack:type_name -> qmeta.transfer.v1.ChunkAck
	8,  // 4: qmeta.transfer.v1.UploadFileResponse.result:type_name -> qmeta.transfer.v1.TransferResult
	2,  // 5: qmeta.transfer.v1.DownloadFileResponse.metadata:type_name -> qmeta.transfer.v1.FileMetadata
	3,  // 6: qmeta.transfer.v1.DownloadFileResponse.chunk:type_name -> qmeta.transfer.v1.ChunkData
	8,  // 7: qmeta.transfer.v1.DownloadFileResponse.result:type_name -> qmeta.transfer.v1.TransferResult
	11, // 8: qmeta.transfer.v1.ListFilesResponse.files:type_name -> qmeta.transfer.v1.ListFileItem
	0,  // 9: qmeta.transfer.v1.FileTransferService.ServerCheck:input_type -> qmeta.transfer.v1.ServerCheckRequest
	12, // 10: qmeta.transfer.v1.FileTransferService.ListFiles:input_type -> qmeta.transfer.v1.ListFilesRequest
	4,  // 11: qmeta.transfer.v1.FileTransferService.UploadFile:input_type -> qmeta.transfer.v1.UploadFileRequest
	9,  // 12: qmeta.transfer.v1.FileTransferService.DownloadFile:input_type -> qmeta.transfer.v1.DownloadFileRequest
	1,  // 13: qmeta.transfer.v1.FileTransferService.ServerCheck:output_type -> qmeta.transfer.v1.ServerCheckResponse
	13, // 14: qmeta.transfer.v1.FileTransferService.ListFiles:output_type -> qmeta.transfer.v1.ListFilesResponse
	5,  // 15: qmeta.transfer.v1.FileTransferService.UploadFile:output_type -> qmeta.transfer.v1.UploadFileResponse
	10, // 16: qmeta.transfer.v1.FileTransferService.DownloadFile:output_type -> qmeta.transfer.v1.DownloadFileResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_qmeta_transfer_v1_transfer_proto_init() }
func file_qmeta_transfer_v1_transfer_proto_init() {
	if File_qmeta_transfer_v1_transfer_proto != nil {
		return
	}
	file_qmeta_transfer_v1_transfer_proto_msgTypes[4].OneofWrappers = []any{
		(*uploadFileRequest_Metadata)(nil),
		(*uploadFileRequest_Chunk)(nil),
	}
	file_qmeta_transfer_v1_transfer_proto_msgTypes[5].OneofWrappers = []any{
		(*uploadFileResponse_MetaAck)(nil),
		(*uploadFileResponse_ChunkAck)(nil),
		(*uploadFileResponse_Result)(nil),
	}
	file_qmeta_transfer_v1_transfer_proto_msgTypes[10].OneofWrappers = []any{
		(*downloadFileResponse_Metadata)(nil),
		(*downloadFileResponse_Chunk)(nil),
		(*downloadFileResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qmeta_transfer_v1_transfer_proto_rawDesc), len(file_qmeta_transfer_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qmeta_transfer_v1_transfer_proto_goTypes,
		DependencyIndexes: file_qmeta_transfer_v1_transfer_proto_depIdxs,
		MessageInfos:      file_qmeta_transfer_v1_transfer_proto_msgTypes,
	}.Build()
	File_qmeta_transfer_v1_transfer_proto = out.File
	file_qmeta_transfer_v1_transfer_proto_goTypes = nil
	file_qmeta_transfer_v1_transfer_proto_depIdxs = nil
}
